version: "3.7"
services:
  database: 
    image: postgres
    restart: always
    env-file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgres/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    deponds_on:
      - database
    networks:
      - default
    ports:
      - "4001:4001"
  volumes:
    data:
