DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS versions;
DROP TABLE IF EXISTS entities;
DROP TABLE IF EXISTS event_types;
DROP TABLE IF EXISTS users_logs;
DROP TABLE IF EXISTS invoices_logs;
