
" install vplug:
" Needed git installed
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" vimrc source and PlugInstall

syntax on
set number
set tabstop=4
set shiftwidth=4
set expandtab
set t_Co=256
set bg=dark
set incsearch " incremental search
set hlsearch  " highlight search
set termwinsize=12x0 " terminal size
set splitbelow " always split below
set mouse=a " mouse drag on window splits


" ============================== RANDOM
set nobackup
set noswapfile
set noundofile

" ============================== MAPPINGS

" Basics
imap jj <Esc>
imap jk <Esc>
imap kl <Esc> 
:nnoremap <Space> :


" Commands
:nnoremap bf :buffers<CR>
:nnoremap bn :bn<CR>
:nnoremap bp :bp<CR>



" Tab Navigation
map <C-L> gt
map <C-H> gT
noremap <C-t> :tabnew<CR>



" ============================== PLUGINS

call plug#begin()
    Plug 'morhetz/gruvbox'
    Plug 'preservim/nerdtree'
call plug#end()



" ============================== NERDTREE
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Open the existing NERDTree on each new Tab
autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

let NERDTreeMapOpenInTab='<ENTER>'


colorscheme gruvbox


" autosource .vimrc after save
autocmd! BufWritePost $MYVIMRC source $MYVIMRC | echom "Reload $NVIMRC"




