// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteAction struct {
	Message string   `json:"message"`
	Status  string   `json:"status"`
	Errors  []*Error `json:"errors"`
}

type Error struct {
	Method  string `json:"method"`
	Message string `json:"message"`
	Field   string `json:"field"`
	Code    int    `json:"code"`
}

type RegisterUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterUserResponse struct {
	Token string `json:"token"`
	ID    string `json:"id"`
	Name  string `json:"name"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserResponse struct {
	User   *User    `json:"user"`
	Errors []*Error `json:"errors"`
}

type UsersResponse struct {
	Users  []*User  `json:"users"`
	Errors []*Error `json:"errors"`
}
