version: '3'
services:
  api:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: './'
    environment:
      - USERNAME=dev
      - PASSWORD=postgres
      - HOST=db
      - SCHEMA=todos_db
    ports:
      - '4001:4001'
    expose:
      - '4001'
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=todos_db
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - '5432'
