version: '3'

secrets:
    broker-service:
        build:
            context: ./../broker-service
            dockerfile: ./../broker-service/brocker-service.dockerfile
        restart: always
        ports:
            - "8080:80"
        deploy:
            mode: replicated
            replicas: 1
