version: '3'

services:
  template-http-mysql:
    container_name: micro-kafka-template-financial-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - dev
  db:
    container_name: micro-kafka-template-db
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root_secret"
      - "MYSQL_USER=dev"
      - "MYSQL_PASSWORD=dev"
      - "MYSQL_DATABASE=project"
    volumes:
      - ../../db-mysql:/var/lib/mysql
      - ../../src/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - dev 
volumes:
  db-mysql:
networks:
  dev:
    driver: bridge